version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:lts  # port 8080
    container_name: jenkins
    hostname: jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins" # in order to support reverse proxy
    volumes:
      - ./jenkins:/var/jenkins_home

  cache-server:
    image: erikaulin/unitycacheserver:latest # port 8126
    container_name: cache-server
    hostname: cache-server
    volumes:
      - ./cache-server:/opt/cache

  web:
    image: nginx
    container_name: nginx
    hostname: nginx
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
